[package]
name = "kyu"
version = "0.1.1"
edition = "2021"
description = "A simple reimplmentation of git in Rust. (Strongly inspired by wyag)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "4.6", features = ["derive"] }
colored = "3.1"
flate2 = { version = "1.1", features = ["zlib"] }
hex-literal = "1.1"
rust-ini = "0.21"
sha1 = "0.11"
